// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P2_AP1_Jefferson_20190267.DAL;

namespace P2_AP1_Jefferson_20190267.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("P2_AP1_Jefferson_20190267.Entidades.DetalleTarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Requerimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tiempo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TiempoTotal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TipoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("TipoId");

                    b.ToTable("DetalleTarea");
                });

            modelBuilder.Entity("P2_AP1_Jefferson_20190267.Entidades.Proyecto", b =>
                {
                    b.Property<int>("ProyectoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.HasKey("ProyectoId");

                    b.ToTable("Proyecto");
                });

            modelBuilder.Entity("P2_AP1_Jefferson_20190267.Entidades.TipoTarea", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoTareaa")
                        .HasColumnType("TEXT");

                    b.HasKey("TipoId");

                    b.ToTable("TipoTarea");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            TipoTareaa = "Analisis"
                        },
                        new
                        {
                            TipoId = 2,
                            TipoTareaa = "Diseño"
                        },
                        new
                        {
                            TipoId = 3,
                            TipoTareaa = "Programacion"
                        },
                        new
                        {
                            TipoId = 4,
                            TipoTareaa = "Prueba"
                        });
                });

            modelBuilder.Entity("P2_AP1_Jefferson_20190267.Entidades.DetalleTarea", b =>
                {
                    b.HasOne("P2_AP1_Jefferson_20190267.Entidades.Proyecto", null)
                        .WithMany("Detalle")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P2_AP1_Jefferson_20190267.Entidades.TipoTarea", "tipoTarea")
                        .WithMany()
                        .HasForeignKey("TipoId");

                    b.Navigation("tipoTarea");
                });

            modelBuilder.Entity("P2_AP1_Jefferson_20190267.Entidades.Proyecto", b =>
                {
                    b.Navigation("Detalle");
                });
#pragma warning restore 612, 618
        }
    }
}
